### ISSUE TITLE
What is the relationship between this and the Anvil editor?

### ISSUE THREAD

**Issue by eddyojb88** [anvilistas/amoni#18]
It is unclear to me the relationship between this package and the Anvil editor from the docs. Once we have started the hello-world app, what are some options for bringing up the GUI editor and starting development? Or is the objective of the package to serve apps?

**Comment by meatballs** [comment]
There is no relationship. Anvil's IDE is only available for apps hosted at anvil.works and there is no option to start it from a local copy.
