### ISSUE TITLE
FATAL:  password authentication failed for user "root"

### ISSUE THREAD

**Issue by thias42** [anvilistas/amoni#21]
Hi,

First of all, thank you for this great project.

I am experiencing an issue on Ubuntu 18.04. When I start a new amoni project with
```
prompt> amoni init demo
prompt> cd demo
prompt> amoni start
```
The app fails to start and I see the following error messages in `docker compose logs`:
```
demo-db-1   | 2023-03-23 17:23:34.902 UTC [88] FATAL:  password authentication failed for user "root"
demo-db-1   | 2023-03-23 17:23:34.902 UTC [88] DETAIL:  Role "root" does not exist.
demo-db-1   |   Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
demo-app-1  | Connection to DB failed. Waiting 1s, then retrying migration...
```
My environment is:
```
Ubuntu 18.04.6 LTS
Python 3.11.0
Docker version 20.10.21, build baeda1f
Docker Compose version v2.16.0
amoni 0.0.13
postgres:latest (2bb008a38e7c)
```
I only see this issue on Ubuntu. It works perfectly fine on macOS.
Do you have an idea what might be the cause for this?

Matthias

**Comment by meatballs** [comment]
I use ubuntu myself - but only 20.04 and 22.04 since amoni was written, so my guess is that it's something to do with 18.04
