### ISSUE TITLE
"amoni start" fails.

### ISSUE THREAD

**Issue by telemix** [anvilistas/amoni#25]
I am following your getting started instructions, and it all seems work right up to the final docker compose up, when I get this : 

```
[+] Running 3/4
 ✔ Network demo_default      Created                                       0.2s 
 ✔ Volume "demo_postgresql"  Created                                       0.0s 
 ✔ Container demo-db-1       Healthy                                       3.2s 
 ⠿ Container demo-app-1      Starting                                      3.9s 
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "anvil-app-server": executable file not found in $PATH: unknown
Traceback (most recent call last):

  File "/home/user/.local/bin/amoni", line 8, in <module>
    sys.exit(cmd())

  File "/home/user/.local/pipx/venvs/amoni/lib/python3.10/site-packages/amoni/cli/amoni.py", line 54, in start
    api.start_service("app", detach=True)

  File "/home/user/.local/pipx/venvs/amoni/lib/python3.10/site-packages/amoni/api.py", line 110, in start_service
    docker.compose.up([name], detach=detach)

  File "/home/user/.local/pipx/venvs/amoni/lib/python3.10/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 737, in up
    run(full_cmd, capture_stdout=quiet, capture_stderr=quiet)

  File "/home/user/.local/pipx/venvs/amoni/lib/python3.10/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(

python_on_whales.exceptions.DockerException: The docker command executed was `/snap/bin/docker compose up --detach app`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).
```
There is an empty error.log file in ./logs.

I'm not sure where the PATH should be pointing, or even which PATH it is referring to (maybe there's one in the container?)

Any help gratefully received...

```
$ docker ps -la
CONTAINER ID   IMAGE      COMMAND                  CREATED          STATUS    PORTS                                       NAMES
073d3f9c4637   demo-app   "anvil-app-server --…"   20 minutes ago   Created   0.0.0.0:3030->3030/tcp, :::3030->3030/tcp   demo-app-1
```
I'm running on Ubuntu 22.04.

**Comment by meatballs** [comment]
I'm away at the moment. I'll have a look at this once I'm back home in a couple of weeks.

**Comment by meatballs** [comment]
Is it possible that creative Procrastination comes to the rescue here? 

https://anvil.works/forum/t/no-module-named-functools-when-using-anvil-app-server/18591/7?u=owen.campbell

**Comment by telemix** [comment]
Possibly :)

Do i need to update the anvil docker image within amoni or do I just pull the latest version of the app server directly in docker (eg something like docker pull) ?

I don;t know how to do either, but it would be good to know that I'm banging my head against the right method ... :) 

--
  David Wylie
  ***@***.***

**Comment by meatballs** [comment]
sorry I can't look into this properly right now. Life is getting in the way.

Try `amoni start --update` which should update the docker image for you.

**Comment by vidz1979** [comment]
Same error here! Ubuntu 22.04 also.

**Comment by jonp92** [comment]
Is Amoni dead? This issue is STILL persisting.

**Comment by meatballs** [comment]
It's open source. Anyone is welcome to contribute.

**Comment by meatballs** [comment]
It looks like the image build failed silently:

https://github.com/anvilistas/amoni/actions/runs/6169626033/job/16744258595#step:6:8961

**Comment by telemix** [comment]
> It looks like the image build failed silently:
> 
> https://github.com/anvilistas/amoni/actions/runs/6169626033/job/16744258595#step:6:8961

Is that something I'm doing wrong?

**Comment by meatballs** [comment]
> > It looks like the image build failed silently:
> > https://github.com/anvilistas/amoni/actions/runs/6169626033/job/16744258595#step:6:8961
> 
> Is that something I'm doing wrong?

Definitely not!

There's a docker image that gets automatically built and deployed whenever the anvil app server itself is updated. The last time that happened, the build failed silently. I don't yet understand why!

**Comment by telemix** [comment]
> > > It looks like the image build failed silently:
> > > https://github.com/anvilistas/amoni/actions/runs/6169626033/job/16744258595#step:6:8961
> > 
> > 
> > Is that something I'm doing wrong?
> 
> Definitely not!
> 
> There's a docker image that gets automatically built and deployed whenever the anvil app server itself is updated. The last time that happened, the build failed silently. I don't yet understand why!

Ah ok. Cheers.

**Comment by meatballs** [comment]
Related: https://anvil.works/forum/t/docker-build-fails-for-anvil-server/19412

**Comment by nickantonaccio** [comment]
I've had some issues running recent versions of anvil-app-server on Ubuntu (no Docker involved).  Have you tried using version 1.7.3?

**Comment by meatballs** [comment]
This should now be fixed. There are new images for both the app server and the db which you can use with:

`amoni start --upgrade`

Watch out if you have an existing db. The new image used postgresql 16 and it will fail to start if you have a db from the older image because that used postgresql 15.

If you only want to upgrade the app server and leave the db untouched, use:

```
docker compose pull app
amoni start
```

**Comment by telemix** [comment]
Just to say it seems to be working fine for me  now as well. Thanks!
